### ISSUE TITLE
Who should I talk to about the project is functional contact number +51925001712 whatsapp

### ISSUE THREAD

**Issue by efrain2007** [lllariogonzalez/e-commerce#1]
Who should I talk to about the project is functional contact number +51925001712 whatsapp

**Comment by lllariogonzalez** [comment]
Dear efrain2007,

The project was designed by a team of 8 developers as part of our final internship in December 2022. However, it has not received any updates since that time. It likely requires several adjustments to become fully functional.

If you're interested, I can connect you with the team members involved in its development.
